# Generated by Django 4.1.2 on 2022-10-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0008_alter_favegames_startyear_alter_modslist_releaseyear"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favegames",
            name="gamename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="name of game/series",
            ),
        ),
        migrations.AlterField(
            model_name="modslist",
            name="game",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="name of game"
            ),
        ),
        migrations.AlterField(
            model_name="modslist",
            name="modname",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="name of mod"
            ),
        ),
    ]
