# Generated by Django 4.1.2 on 2022-10-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0009_alter_favegames_gamename_alter_modslist_game_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favegames",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="modslist",
            options={"ordering": ("id",)},
        ),
    ]
