# Generated by Django 4.0.5 on 2022-10-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0010_alter_favegames_options_alter_modslist_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="modslist",
            new_name="modslists",
        ),
    ]
