# Generated by Django 4.0.5 on 2022-10-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0011_rename_modslist_modslists"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="favegames",
            new_name="favgames",
        ),
    ]
