# Generated by Django 4.1.2 on 2022-10-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0012_rename_favegames_favgames"),
    ]

    operations = [
        migrations.CreateModel(
            name="graphs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graphlink", models.JSONField()),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
