# Generated by Django 4.1.2 on 2022-10-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0013_graphs"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphs",
            name="graphname",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="graph name",
            ),
        ),
    ]
