# Generated by Django 4.1.2 on 2022-10-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0014_graphs_graphname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphs",
            name="graphlink",
            field=models.TextField(),
        ),
    ]
