# Generated by Django 4.1.2 on 2022-10-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0015_alter_graphs_graphlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphs",
            name="graphlink",
            field=models.ImageField(upload_to="static/images/graphs"),
        ),
    ]
