# Generated by Django 4.1.2 on 2022-10-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0016_alter_graphs_graphlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graphs",
            name="graphname",
        ),
    ]
