# Generated by Django 4.1.2 on 2022-10-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0017_remove_graphs_graphname"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphs",
            name="graphname",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="name of chart",
            ),
        ),
    ]
