# Generated by Django 4.1.2 on 2022-10-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0018_graphs_graphname"),
    ]

    operations = [
        migrations.CreateModel(
            name="modeltimerecordscsv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user", models.CharField(max_length=200)),
                ("minutes", models.IntegerField()),
                ("ticket", models.IntegerField()),
                ("code", models.CharField(max_length=200)),
                ("billable", models.CharField(max_length=200)),
            ],
        ),
    ]
