# Generated by Django 4.1.2 on 2022-10-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypages", "0023_alter_modeltimerecordscsv_minutes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="modeltimerecordscsv",
            new_name="modeltimerecordscsvs",
        ),
    ]
